### ISSUE TITLE
Panic Discovered

### ISSUE THREAD

**Issue by bonedaddy** [bonedaddy/bettercap#1]
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a7684]
goroutine 18083 [running]:
encoding/json.(*encodeState).marshal.func1(0x34dcdbc)
        /usr/local/go/src/encoding/json/encode.go:326 +0x78
panic(0x77eb50, 0xecabc0)
        /usr/local/go/src/runtime/panic.go:969 +0x158
encoding/json.(*encodeState).marshal.func1(0x34dcc70)
        /usr/local/go/src/encoding/json/encode.go:326 +0x78
panic(0x77eb50, 0xecabc0)
        /usr/local/go/src/runtime/panic.go:969 +0x158
encoding/json.(*encodeState).string(0x38d1a40, 0x0, 0x4, 0x1)
        /usr/local/go/src/encoding/json/encode.go:1004 +0x4c
encoding/json.stringEncoder(0x38d1a40, 0x750d48, 0x397b260, 0x198, 0x100)
        /usr/local/go/src/encoding/json/encode.go:645 +0x14c
encoding/json.structEncoder.encode(0x3532000, 0x14, 0x20, 0x3097f80, 0x38d1a40, 0x808a28, 0x364db00, 0x99, 0x800100)
        /usr/local/go/src/encoding/json/encode.go:759 +0x214
encoding/json.(*encodeState).reflectValue(0x38d1a40, 0x808a28, 0x364db00, 0x99, 0x38d0100)
        /usr/local/go/src/encoding/json/encode.go:358 +0x68
encoding/json.(*encodeState).marshal(0x38d1a40, 0x808a28, 0x364db00, 0x34a0100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:330 +0xe4
encoding/json.Marshal(0x808a28, 0x364db00, 0x808a28, 0x364db00, 0x6, 0x3768df0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:161 +0x40
github.com/bettercap/bettercap/network.(*AccessPoint).MarshalJSON(0x3713d10, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/kali/go/src/github.com/bonedaddy/bettercap/network/wifi_ap.go:48 +0x1dc
encoding/json.marshalerEncoder(0x38d1aa0, 0x8181e8, 0x3713d10, 0x16, 0xf20100)
        /usr/local/go/src/encoding/json/encode.go:477 +0x88
encoding/json.(*encodeState).reflectValue(0x38d1aa0, 0x8181e8, 0x3713d10, 0x16, 0x38d0100)
        /usr/local/go/src/encoding/json/encode.go:358 +0x68
encoding/json.(*encodeState).marshal(0x38d1aa0, 0x8181e8, 0x3713d10, 0x100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:330 +0xe4
encoding/json.Marshal(0x8181e8, 0x3713d10, 0x12, 0xffffffff, 0x34041e0, 0x1, 0xa)
        /usr/local/go/src/encoding/json/encode.go:161 +0x40
github.com/bettercap/bettercap/modules/events_stream.(*TriggerList).Dispatch(0x33a2570, 0x87908a, 0xb, 0x84281d80, 0xbff166e9, 0x12b64a9b, 0x17b, 0xf24a38, 0x8181e8, 0x3713d10, ...)
        /home/kali/go/src/github.com/bonedaddy/bettercap/modules/events_stream/trigger_list.go:112 +0x224
github.com/bettercap/bettercap/modules/events_stream.(*EventsStream).dispatchTriggers(0x3125b90, 0x87908a, 0xb, 0x84281d80, 0xbff166e9, 0x12b64a9b, 0x17b, 0xf24a38, 0x8181e8, 0x3713d10)
        /home/kali/go/src/github.com/bonedaddy/bettercap/modules/events_stream/events_triggers.go:52 +0x30
created by github.com/bettercap/bettercap/modules/events_stream.(*EventsStream).Start.func1
        /home/kali/go/src/github.com/bonedaddy/bettercap/modules/events_stream/events_stream.go:300 +0xb8
```

**Comment by bonedaddy** [comment]
I think the issue stems from [here](https://github.com/bonedaddy/bettercap/blob/master-blaster/modules/events_stream/trigger_list.go#L112) when `e.Data` is `nil`, OR it stems from [this function](https://github.com/bonedaddy/bettercap/blob/master-blaster/network/wifi_ap.go#L34) however I don't *think* its that as it doesnt seem to make sense why that would be failing?
